# Generated by Django 2.1 on 2022-06-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jitterbunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
